"""
main.py  —  CineScope FastAPI Backend
──────────────────────────────────────────────────────────────────
Run:
    uvicorn main:app --reload --port 8000

The server loads all ML artifacts once at startup (takes ~2-5 s
depending on dataset size) and then serves every request from
in-memory data structures — no disk I/O per request.

Endpoints
──────────────────────────────────────────────────────────────────
GET  /health                          → server status + model info
GET  /search?q=inception&limit=10     → title search
GET  /movie/{movie_id}                → full movie metadata
GET  /similar/{movie_id}?limit=10     → TF-IDF cosine neighbours
GET  /cluster/{movie_id}?limit=10     → K-Means cluster feed
GET  /clusters                        → summary of all clusters
POST /similar-text                    → similarity from free text
"""

import os
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from recommender import CineScopeRecommender

# ── Global recommender instance ───────────────────────────────────────────────
# Loaded once during startup via the lifespan handler below.
rec: Optional[CineScopeRecommender] = None

ARTIFACTS_DIR = os.getenv("ARTIFACTS_DIR", "artifacts")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load ML artifacts at startup, release on shutdown."""
    global rec
    try:
        rec = CineScopeRecommender(ARTIFACTS_DIR)
    except FileNotFoundError as e:
        print(f"⚠️  {e}")
        print("   Server will start but all ML endpoints will return 503.")
    yield
    # Nothing to clean up — artifacts are read-only in memory


# ── App factory ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="CineScope Recommendation API",
    description=(
        "Serves TF-IDF cosine similarity and K-Means cluster recommendations "
        "from pre-trained ML artifacts generated by the CapstoneFinal notebook."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow the Vite dev server (port 5173) and any deployed origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:3000",
        "http://127.0.0.1:5173",
        "*",  # remove in production and list exact origins
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── Dependency guard ──────────────────────────────────────────────────────────
def require_rec() -> CineScopeRecommender:
    if rec is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "ML model not loaded. Run the Jupyter notebook to generate "
                f"artifacts in '{ARTIFACTS_DIR}/', then restart the server."
            ),
        )
    return rec


# ── Request / Response models ─────────────────────────────────────────────────
class SimilarTextRequest(BaseModel):
    text: str
    limit: int = 10


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    """Server status and model info. Safe to call before artifacts are loaded."""
    if rec is None:
        return {
            "status":  "degraded",
            "message": f"Artifacts not found in '{ARTIFACTS_DIR}/'. "
                       "Run the notebook to generate them.",
            "model":   None,
        }
    return {
        "status":  "ok",
        "model": {
            "movies":     len(rec.meta_df),
            "vocab_size": len(rec.tfidf.vocabulary_),
            "clusters":   rec.n_clusters,
            "artifacts":  str(Path(ARTIFACTS_DIR).resolve()),
        },
    }


@app.get("/search")
def search(
    q:     str = Query(..., description="Partial title query"),
    limit: int = Query(10,  ge=1, le=50),
):
    """
    Case-insensitive partial title search across all movies in the
    training set, sorted by popularity.

    Uses the movies_metadata.parquet loaded at startup — no index
    is consulted, just a vectorised string contains check.
    """
    r = require_rec()
    try:
        return r.search(q, limit=limit)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/movie/{movie_id}")
def get_movie(movie_id: int):
    """
    Full metadata for a single movie: title, genres, director, cast,
    overview, vote_average, cluster, silhouette score.
    """
    r = require_rec()
    try:
        return r.get_movie(movie_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"movie_id {movie_id} not found")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/similar/{movie_id}")
def similar_movies(
    movie_id: int,
    limit:    int = Query(10, ge=1, le=50),
):
    """
    Top-N content-similar movies using pre-computed TF-IDF cosine similarity.

    Algorithm:
      During training the notebook computed pairwise cosine similarities
      between all TF-IDF vectors and stored the top-100 neighbours per movie
      in cosine_topk_index.json. This endpoint does an O(1) dict lookup —
      there is no computation at serving time.

    The similarity score is the cosine similarity (0–1) between the
    two movies' TF-IDF soup vectors.
    """
    r = require_rec()
    try:
        return r.similar_movies(movie_id, limit=limit)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"movie_id {movie_id} not found")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/cluster/{movie_id}")
def cluster_feed(
    movie_id: int,
    limit:    int = Query(10, ge=1, le=50),
    sort:     str = Query("silhouette", regex="^(silhouette|popularity|vote_average)$"),
):
    """
    Movies in the same K-Means cluster as the input, sorted by cluster fit.

    Algorithm:
      K-Means was trained on a combined feature matrix:
        [TF-IDF soup vector | scaled(avg_rating, rating_count, year)]
      Each movie belongs to one of N clusters. Movies in the same cluster
      share similar genre/keyword/content AND similar audience metrics.

      Silhouette score (−1 to 1) measures how tightly the movie fits its
      own cluster vs the next nearest cluster. Sorting by silhouette surfaces
      the most "archetypal" members of the cluster first.
    """
    r = require_rec()
    try:
        return r.cluster_feed(movie_id, limit=limit, sort=sort)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"movie_id {movie_id} not found")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/clusters")
def get_clusters():
    """
    Summary of all K-Means clusters: size, top genres, avg rating,
    avg silhouette score, and best-fit representative movie.
    """
    r = require_rec()
    try:
        return r.get_cluster_summary()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/similar-text")
def similar_by_text(body: SimilarTextRequest):
    """
    Find movies similar to an arbitrary text description.

    The query is transformed by the same TF-IDF vectorizer used during
    training and compared against the full movie matrix using cosine
    similarity. Useful for 'describe what you want' search.

    Example body:
        { "text": "space exploration survival drama", "limit": 10 }
    """
    r = require_rec()
    try:
        return r.realtime_similar(body.text, limit=body.limit)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Dev runner ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
