"""
recommender.py
──────────────────────────────────────────────────────────────────
CineScopeRecommender — loads all trained ML artifacts once at
startup and exposes fast recommendation methods.

Artifacts expected in the artifacts/ directory (generated by the
Jupyter notebook CapstoneFinal_MovieLens.ipynb):

    tfidf_vectorizer.pkl      – fitted TF-IDF vectorizer
    tfidf_matrix.npz          – sparse TF-IDF matrix (movies × vocab)
    cosine_topk_index.json    – top-100 cosine neighbours per movie
    kmeans.pkl                – fitted K-Means model
    scaler.pkl                – StandardScaler for numeric features
    movies_metadata.parquet   – full movie metadata + cluster labels
    movie_ml.parquet          – lightweight cluster/silhouette sidecar
    title_to_index.json       – title string → row index
    index_to_movie_id.json    – row index → movieId

Model summary
──────────────────────────────────────────────────────────────────
TF-IDF + Cosine Similarity
  Each movie is represented as a sparse vector over a vocabulary
  built from its genre-keyword-cast-director-overview "soup".
  Cosine similarity between vectors gives content-based neighbours.
  The top-100 neighbours are pre-computed and stored in
  cosine_topk_index.json for O(1) lookup at serving time.

K-Means Clustering
  Movies are clustered using their TF-IDF vector stacked with
  scaled numeric features (avg_rating, rating_count, year).
  Silhouette scores measure how well each movie fits its cluster.
  cluster_feed() returns same-cluster peers sorted by silhouette —
  the best representatives of the genre/era neighbourhood.
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import scipy.sparse as sp


class CineScopeRecommender:
    """
    Stateless recommender — loads artifacts once, serves instantly.
    Thread-safe for concurrent FastAPI requests (read-only after init).
    """

    def __init__(self, artifacts_dir: str = "backend/artifacts"):
        art = Path(artifacts_dir)
        if not art.exists():
            raise FileNotFoundError(
                f"Artifacts directory not found: {art.resolve()}\n"
                "Run the Jupyter notebook to generate the artifacts first."
            )

        print(f"Loading artifacts from {art.resolve()} ...")

        # ── ML models ─────────────────────────────────────────────────────
        self.tfidf         = joblib.load(art / "tfidf_vectorizer.pkl")
        self.tfidf_matrix  = sp.load_npz(str(art / "tfidf_matrix.npz"))
        self.kmeans        = joblib.load(art / "kmeans.pkl")
        self.scaler        = joblib.load(art / "scaler.pkl")

        # ── Pre-computed cosine neighbour index ────────────────────────────
        # Format: { row_index: [(neighbour_row_index, cosine_score), ...] }
        with open(art / "cosine_topk_index.json") as f:
            raw = json.load(f)
            self.cosine_topk = {int(k): v for k, v in raw.items()}

        # ── Movie metadata ─────────────────────────────────────────────────
        self.meta_df = pd.read_parquet(art / "movies_metadata.parquet")
        self.ml_df   = pd.read_parquet(art / "movie_ml.parquet")

        # ── Lookup maps ────────────────────────────────────────────────────
        with open(art / "title_to_index.json") as f:
            self.title_to_index = json.load(f)

        with open(art / "index_to_movie_id.json") as f:
            self.index_to_movie_id = {int(k): v for k, v in json.load(f).items()}

        self.movie_id_to_index = {v: k for k, v in self.index_to_movie_id.items()}

        # Cluster count from the fitted model
        self.n_clusters = int(self.kmeans.n_clusters)

        print(
            f"✅ Ready — {len(self.meta_df):,} movies | "
            f"{len(self.tfidf.vocabulary_):,} vocab terms | "
            f"{self.n_clusters} clusters"
        )

    # ── Internal helpers ───────────────────────────────────────────────────

    def _resolve_index(self, title_or_id) -> int:
        """Resolve a movie title (str) or movieId (int) to a DataFrame row index."""
        if isinstance(title_or_id, str):
            if title_or_id not in self.title_to_index:
                raise KeyError(f"Title not found: '{title_or_id}'")
            return self.title_to_index[title_or_id]
        else:
            mid = int(title_or_id)
            if mid not in self.movie_id_to_index:
                raise KeyError(f"movie_id not found: {mid}")
            return self.movie_id_to_index[mid]

    def _row(self, idx: int) -> dict:
        """Return a metadata dict for a given row index, JSON-serialisable."""
        row = self.meta_df.iloc[idx].to_dict()
        # Convert numpy types → Python natives so FastAPI can serialise them
        return {
            k: (
                v.item() if isinstance(v, (np.integer, np.floating))
                else (v.tolist() if isinstance(v, (np.ndarray, list)) else v)
            )
            for k, v in row.items()
        }

    # ── Public API methods ─────────────────────────────────────────────────

    def search(self, query: str, limit: int = 10) -> list[dict]:
        """
        Case-insensitive partial title search.
        Returns movies sorted by popularity descending.
        """
        q    = query.lower()
        mask = self.meta_df["title"].str.lower().str.contains(q, na=False)
        cols = ["movie_id", "title", "vote_average", "popularity", "cluster"]
        existing = [c for c in cols if c in self.meta_df.columns]
        result = (
            self.meta_df[mask][existing]
            .sort_values("popularity", ascending=False)
            .head(limit)
        )
        return result.to_dict(orient="records")

    def get_movie(self, movie_id: int) -> dict:
        """Full metadata for a single movie by movieId."""
        idx = self._resolve_index(movie_id)
        return self._row(idx)

    def similar_movies(self, movie_id: int, limit: int = 10) -> list[dict]:
        """
        Top-N content-similar movies using the pre-computed cosine index.

        How it works:
          The cosine_topk_index was built from pairwise cosine similarities
          over the TF-IDF matrix. Each entry stores the top-100 most similar
          movies for every film. This is an O(1) lookup — no computation at
          serving time, just a dict read.
        """
        idx       = self._resolve_index(movie_id)
        neighbors = self.cosine_topk.get(idx, [])[:limit]

        rows = []
        for nb_idx, score in neighbors:
            row = self._row(nb_idx)
            rows.append({
                "movie_id":     row["movie_id"],
                "title":        row["title"],
                "similarity":   round(float(score), 4),
                "vote_average": row.get("vote_average", 0),
                "popularity":   row.get("popularity", 0),
                "cluster":      row.get("cluster", -1),
                "genres":       row.get("genres_list", []),
            })
        return rows

    def cluster_feed(
        self,
        movie_id: int,
        limit: int = 10,
        sort: str = "silhouette",
    ) -> list[dict]:
        """
        Movies in the same K-Means cluster as the input film, sorted by
        cluster fit (silhouette score) by default.

        How it works:
          K-Means grouped all movies into N clusters based on their combined
          TF-IDF + numeric feature vector. Movies in the same cluster share
          similar genre/keyword/cast profiles AND era/popularity signals.
          Silhouette score measures how tightly a movie fits its cluster vs
          how loosely it fits neighbouring clusters — higher = better fit.

        sort options: 'silhouette' | 'popularity' | 'vote_average'
        """
        idx     = self._resolve_index(movie_id)
        src_row = self._row(idx)
        src_id  = src_row["movie_id"]
        cluster = src_row.get("cluster", -1)

        if cluster == -1:
            return []

        peers = self.meta_df[
            (self.meta_df["cluster"] == cluster) &
            (self.meta_df["movie_id"] != src_id)
        ].copy()

        valid_sorts = {"silhouette", "popularity", "vote_average"}
        sort_col    = sort if sort in valid_sorts else "silhouette"
        if sort_col in peers.columns:
            peers = peers.sort_values(sort_col, ascending=False)

        cols     = ["movie_id", "title", "silhouette", "cluster", "vote_average", "popularity"]
        existing = [c for c in cols if c in peers.columns]
        return peers[existing].head(limit).to_dict(orient="records")

    def get_cluster_summary(self) -> list[dict]:
        """
        Summary of all K-Means clusters: size, top genres, best-fit title.
        Useful for the frontend's cluster browsing feature.
        """
        summary = []
        for c in sorted(self.meta_df["cluster"].unique()):
            g = self.meta_df[self.meta_df["cluster"] == c]

            # Best-fit movie = highest silhouette in this cluster
            best_title = ""
            if "silhouette" in g.columns and len(g) > 0:
                best_title = g.loc[g["silhouette"].idxmax(), "title"]

            # Top genres across the cluster
            all_genres: list = []
            if "genres_list" in g.columns:
                for gl in g["genres_list"].dropna():
                    if isinstance(gl, list):
                        all_genres.extend(gl)

            top_genres = (
                pd.Series(all_genres).value_counts().index[:3].tolist()
                if all_genres else []
            )

            summary.append({
                "cluster":    int(c),
                "n_movies":   len(g),
                "top_genres": top_genres,
                "avg_rating": round(float(g["vote_average"].mean()), 2)
                              if "vote_average" in g.columns else 0.0,
                "avg_sil":    round(float(g["silhouette"].mean()), 4)
                              if "silhouette" in g.columns else 0.0,
                "best_fit":   best_title,
            })
        return summary

    def realtime_similar(self, soup_text: str, limit: int = 10) -> list[dict]:
        """
        Compute cosine similarity on-the-fly for an arbitrary text query.
        Used for 'find movies similar to this description' feature.

        How it works:
          The query text is transformed by the same TF-IDF vectorizer used
          during training. The resulting vector is compared against the full
          tfidf_matrix using a dot product (valid because TF-IDF vectors are
          already L2-normalised by sklearn). The top-limit results are returned.
        """
        from sklearn.metrics.pairwise import linear_kernel

        query_vec = self.tfidf.transform([soup_text])         # (1, vocab)
        sims      = linear_kernel(query_vec, self.tfidf_matrix).flatten()  # (n_movies,)
        top_idx   = np.argsort(sims)[::-1][:limit]

        rows = []
        for idx in top_idx:
            if sims[idx] < 0.01:
                break
            row = self._row(int(idx))
            rows.append({
                "movie_id":   row["movie_id"],
                "title":      row["title"],
                "similarity": round(float(sims[idx]), 4),
                "genres":     row.get("genres_list", []),
                "cluster":    row.get("cluster", -1),
            })
        return rows
